const phraseCorrections: Array<[RegExp, string]> = [
  [/\bhippa\b/gi, 'HIPAA'],
  [/\bhipaa\b/gi, 'HIPAA'],
  [/\ba\s*1\s*c\b/gi, 'A1C'],
  [/\bhba\s*1\s*c\b/gi, 'HbA1c'],
  [/\bmet\s*form\s*in\b/gi, 'metformin'],
  [/\bmetaformin\b/gi, 'metformin'],
  [/\batorva\s*statin\b/gi, 'atorvastatin'],
  [/\bamox\s*icillin\b/gi, 'amoxicillin'],
  [/\bepi\s*pen\b/gi, 'EpiPen'],
  [/\btylenol\b/gi, 'Tylenol'],
  [/\bibuprofen\b/gi, 'ibuprofen'],
  [/\badvil\b/gi, 'Advil'],
  [/\blasix\b/gi, 'Lasix'],
  [/\bcopd\b/gi, 'COPD'],
  [/\bgerd\b/gi, 'GERD'],
  [/\bdnr\b/gi, 'DNR'],
  [/\bmri\b/gi, 'MRI'],
  [/\bct scan\b/gi, 'CT scan'],
  [/\bekg\b/gi, 'EKG'],
  [/\becg\b/gi, 'ECG'],
];

export const medicalHotwords = [
  'A one C',
  'acetaminophen',
  'Advil',
  'allergy',
  'amoxicillin',
  'atorvastatin',
  'asthma',
  'blood pressure',
  'chief complaint',
  'COPD',
  'CT scan',
  'DNR',
  'diabetes',
  'dyspnea',
  'dysuria',
  'ECG',
  'EKG',
  'EpiPen',
  'GERD',
  'H B A one C',
  'hemoptysis',
  'hematuria',
  'hypertension',
  'hypotension',
  'hypoglycemia',
  'HIPAA',
  'ibuprofen',
  'Lasix',
  'metformin',
  'MRI',
  'nausea',
  'neuropathy',
  'palpitations',
  'pharmacy',
  'prescription',
  'pneumonia',
  'primary care physician',
  'shortness of breath',
  'Tylenol',
];

export function applyMedicalTerminologyCorrection(transcript: string) {
  return phraseCorrections.reduce(
    (corrected, [pattern, replacement]) =>
      corrected.replace(pattern, replacement),
    transcript,
  );
}
